spring:
  application:
    name: finance_tracker_spring
  datasource:
    url: jdbc:postgresql://localhost:5433/finance_db
    username: finance_user
    password: finance_password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog.xml

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

